-- 2. inserting sample data

INSERT INTO Teams (team_name) VALUES ('Lions');
INSERT INTO Teams (team_name) VALUES ('Tigers');
INSERT INTO Teams (team_name) VALUES ('Panthers');
INSERT INTO Teams (team_name) VALUES ('Sharks');
INSERT INTO Teams (team_name) VALUES ('Wolves');
INSERT INTO Teams (team_name) VALUES ('Dragons');
INSERT INTO Teams (team_name) VALUES ('Eagles');
INSERT INTO Teams (team_name) VALUES ('Cheetahs');
INSERT INTO Teams (team_name) VALUES ('Bulls');
INSERT INTO Teams (team_name) VALUES ('Rhinos');
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_1', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_2', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_3', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_4', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_5', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_6', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_7', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_8', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_9', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_10', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_11', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_12', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_13', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_14', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_1_15', 1);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_1', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_2', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_3', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_4', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_5', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_6', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_7', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_8', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_9', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_10', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_11', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_12', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_13', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_14', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_2_15', 2);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_1', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_2', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_3', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_4', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_5', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_6', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_7', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_8', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_9', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_10', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_11', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_12', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_13', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_14', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_3_15', 3);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_1', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_2', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_3', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_4', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_5', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_6', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_7', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_8', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_9', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_10', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_11', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_12', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_13', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_14', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_4_15', 4);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_1', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_2', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_3', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_4', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_5', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_6', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_7', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_8', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_9', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_10', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_11', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_12', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_13', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_14', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_5_15', 5);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_1', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_2', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_3', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_4', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_5', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_6', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_7', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_8', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_9', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_10', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_11', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_12', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_13', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_14', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_6_15', 6);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_1', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_2', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_3', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_4', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_5', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_6', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_7', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_8', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_9', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_10', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_11', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_12', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_13', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_14', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_7_15', 7);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_1', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_2', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_3', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_4', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_5', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_6', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_7', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_8', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_9', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_10', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_11', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_12', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_13', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_14', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_8_15', 8);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_1', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_2', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_3', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_4', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_5', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_6', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_7', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_8', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_9', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_10', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_11', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_12', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_13', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_14', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_9_15', 9);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_1', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_2', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_3', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_4', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_5', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_6', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_7', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_8', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_9', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_10', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_11', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_12', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_13', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_14', 10);
INSERT INTO Players (player_name, team_id) VALUES ('Player_10_15', 10);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-02', 2, 10, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-03', 1, 3, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-04', 8, 2, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-05', 5, 1, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-06', 7, 8, 8);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-07', 6, 4, 4);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-08', 9, 3, 3);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-09', 4, 9, 4);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-10', 2, 3, 3);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-11', 8, 10, 8);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-12', 7, 5, 7);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-13', 5, 2, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-14', 2, 9, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-15', 10, 2, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-16', 2, 8, 2);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-17', 7, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-18', 6, 4, 4);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-19', 6, 7, 7);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-20', 3, 1, 3);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-21', 1, 6, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-22', 9, 6, 9);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-23', 5, 3, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-24', 5, 7, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-25', 6, 9, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-26', 6, 1, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-27', 1, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-28', 6, 7, 7);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-29', 10, 1, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-30', 9, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-01-31', 2, 1, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-01', 4, 10, 10);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-02', 3, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-03', 4, 5, 4);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-04', 1, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-05', 5, 10, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-06', 9, 8, 9);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-07', 6, 3, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-08', 6, 3, 3);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-09', 7, 5, 5);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-10', 2, 6, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-11', 6, 3, 3);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-12', 9, 8, 9);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-13', 9, 4, 9);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-14', 1, 6, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-15', 4, 1, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-16', 4, 1, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-17', 1, 4, 1);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-18', 6, 7, 7);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-19', 7, 6, 6);
INSERT INTO Matches (match_date, team1_id, team2_id, winner_id) VALUES ('2025-02-20', 10, 3, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 13, 84, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 65, 30, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 15, 3, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 17, 32, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 57, 5, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 36, 82, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 53, 0, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 123, 12, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 52, 66, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 127, 46, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 58, 5, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 100, 94, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 54, 19, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 86, 21, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 46, 15, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 22, 82, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 79, 17, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 129, 36, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 10, 22, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (1, 119, 12, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 101, 96, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 91, 46, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 43, 55, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 72, 3, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 60, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 139, 94, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 95, 80, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 63, 22, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 69, 42, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 48, 66, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 10, 64, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 2, 67, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 141, 5, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 111, 22, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 129, 84, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 99, 35, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 14, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 12, 88, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 113, 98, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (2, 34, 40, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 58, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 46, 26, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 18, 23, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 54, 7, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 86, 35, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 7, 36, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 41, 58, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 129, 20, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 17, 65, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 106, 22, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 29, 44, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 31, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 93, 69, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 149, 55, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 68, 6, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 102, 78, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 148, 31, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 114, 11, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 96, 17, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (3, 13, 76, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 134, 83, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 15, 90, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 137, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 139, 39, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 59, 4, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 76, 20, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 75, 18, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 5, 48, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 132, 11, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 54, 0, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 7, 88, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 147, 93, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 130, 15, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 24, 33, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 85, 98, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 35, 68, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 100, 52, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 53, 40, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 103, 45, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (4, 21, 50, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 89, 71, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 34, 83, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 147, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 32, 9, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 125, 27, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 132, 64, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 55, 6, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 148, 96, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 42, 48, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 127, 89, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 20, 53, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 62, 64, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 49, 92, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 61, 34, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 133, 31, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 22, 23, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 33, 21, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 70, 63, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 115, 48, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (5, 138, 44, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 5, 12, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 48, 20, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 108, 92, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 110, 17, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 38, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 74, 30, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 70, 64, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 56, 84, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 87, 27, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 134, 94, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 26, 49, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 30, 71, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 132, 38, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 46, 35, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 94, 18, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 128, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 122, 67, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 140, 48, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 112, 6, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (6, 43, 39, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 101, 71, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 100, 19, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 25, 6, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 114, 1, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 33, 98, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 97, 7, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 109, 30, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 39, 77, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 38, 21, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 35, 57, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 23, 21, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 11, 32, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 22, 83, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 78, 96, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 91, 93, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 59, 56, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 150, 10, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 142, 76, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 32, 58, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (7, 4, 91, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 125, 8, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 43, 51, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 105, 16, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 16, 67, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 124, 3, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 60, 35, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 141, 11, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 47, 100, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 33, 61, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 108, 49, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 1, 35, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 116, 49, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 53, 70, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 102, 50, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 31, 77, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 95, 32, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 39, 66, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 42, 85, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 142, 82, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (8, 36, 97, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 90, 79, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 26, 1, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 85, 67, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 43, 36, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 102, 62, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 21, 87, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 66, 47, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 150, 32, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 76, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 103, 14, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 78, 91, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 52, 73, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 87, 52, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 139, 9, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 54, 88, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 124, 43, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 125, 19, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 4, 38, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 68, 7, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (9, 10, 54, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 33, 19, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 128, 89, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 75, 1, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 52, 40, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 21, 33, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 32, 55, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 130, 78, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 94, 33, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 122, 90, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 108, 100, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 141, 63, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 13, 82, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 48, 8, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 46, 77, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 118, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 44, 98, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 113, 85, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 23, 4, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 66, 8, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (10, 59, 31, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 146, 18, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 56, 30, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 109, 37, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 63, 17, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 66, 35, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 132, 75, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 18, 40, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 32, 4, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 86, 84, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 119, 91, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 137, 94, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 74, 94, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 105, 29, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 36, 22, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 12, 88, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 147, 95, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 28, 5, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 79, 28, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 99, 96, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (11, 80, 75, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 16, 87, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 86, 29, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 110, 0, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 73, 93, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 4, 48, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 104, 96, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 105, 19, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 19, 90, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 17, 45, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 115, 82, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 100, 12, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 117, 75, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 15, 23, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 24, 87, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 58, 88, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 98, 89, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 116, 69, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 68, 11, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 1, 55, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (12, 12, 44, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 126, 26, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 83, 6, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 1, 56, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 89, 34, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 20, 35, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 34, 92, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 90, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 74, 47, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 108, 15, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 107, 11, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 3, 81, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 138, 51, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 127, 8, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 71, 15, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 75, 43, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 45, 88, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 106, 59, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 24, 95, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 124, 2, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (13, 32, 47, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 43, 85, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 24, 4, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 31, 13, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 88, 79, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 85, 86, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 57, 99, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 52, 34, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 78, 29, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 127, 63, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 30, 43, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 120, 12, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 63, 92, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 46, 79, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 67, 87, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 84, 46, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 90, 47, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 144, 82, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 125, 21, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 27, 56, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (14, 55, 66, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 146, 78, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 45, 1, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 9, 18, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 114, 66, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 36, 59, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 94, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 55, 3, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 150, 45, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 126, 53, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 7, 16, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 14, 2, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 21, 98, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 47, 82, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 67, 13, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 80, 47, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 57, 56, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 131, 62, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 44, 31, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 98, 23, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (15, 58, 66, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 116, 63, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 99, 51, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 137, 81, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 46, 90, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 135, 20, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 90, 54, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 105, 44, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 114, 85, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 106, 57, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 45, 62, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 38, 71, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 54, 53, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 96, 15, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 123, 81, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 76, 3, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 20, 69, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 98, 84, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 86, 17, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 94, 48, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (16, 108, 44, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 61, 67, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 2, 90, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 35, 15, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 104, 3, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 56, 8, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 127, 30, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 59, 31, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 64, 29, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 62, 81, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 141, 26, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 27, 48, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 44, 62, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 68, 49, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 70, 38, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 105, 97, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 63, 66, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 46, 23, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 74, 92, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 10, 12, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (17, 143, 8, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 25, 80, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 92, 38, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 146, 13, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 70, 6, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 97, 21, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 56, 89, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 36, 71, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 76, 6, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 140, 21, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 82, 83, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 51, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 79, 57, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 131, 15, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 105, 54, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 101, 68, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 78, 47, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 103, 9, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 148, 23, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 60, 93, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (18, 123, 56, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 61, 69, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 60, 61, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 28, 8, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 119, 51, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 138, 40, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 54, 14, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 24, 88, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 88, 14, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 27, 16, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 99, 15, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 136, 16, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 74, 37, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 11, 48, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 96, 66, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 43, 96, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 105, 7, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 80, 47, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 16, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 36, 97, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (19, 51, 90, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 138, 89, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 150, 16, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 46, 38, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 100, 4, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 31, 58, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 102, 69, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 125, 4, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 90, 51, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 24, 44, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 139, 71, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 114, 90, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 25, 86, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 60, 72, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 7, 45, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 121, 21, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 136, 69, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 142, 11, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 148, 88, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 113, 66, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (20, 66, 91, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 63, 49, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 101, 83, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 61, 36, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 115, 35, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 2, 22, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 130, 61, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 67, 49, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 58, 91, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 90, 66, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 20, 40, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 6, 39, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 111, 90, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 55, 16, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 41, 6, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 88, 95, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 34, 78, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 77, 91, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 49, 37, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 40, 93, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (21, 52, 7, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 16, 84, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 34, 9, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 101, 27, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 120, 75, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 119, 3, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 104, 73, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 126, 17, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 27, 19, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 1, 27, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 46, 37, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 141, 42, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 24, 29, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 76, 46, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 30, 64, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 100, 16, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 9, 26, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 29, 98, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 133, 23, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 89, 90, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (22, 5, 63, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 33, 25, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 55, 65, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 31, 21, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 102, 75, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 74, 8, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 127, 27, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 49, 98, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 93, 28, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 145, 44, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 77, 47, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 73, 13, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 82, 95, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 90, 36, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 60, 31, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 126, 20, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 39, 97, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 7, 78, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 11, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 144, 25, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (23, 71, 50, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 22, 3, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 149, 41, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 127, 23, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 146, 78, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 115, 96, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 103, 20, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 141, 42, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 145, 15, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 136, 16, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 81, 6, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 62, 47, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 6, 56, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 144, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 1, 85, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 55, 17, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 114, 29, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 118, 55, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 2, 29, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 42, 35, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (24, 50, 84, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 102, 21, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 107, 13, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 96, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 53, 5, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 46, 87, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 19, 72, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 85, 49, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 126, 72, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 15, 8, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 59, 25, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 47, 47, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 98, 29, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 63, 36, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 80, 23, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 91, 50, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 5, 17, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 76, 12, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 23, 25, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 58, 69, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (25, 65, 15, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 140, 87, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 61, 4, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 142, 65, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 104, 60, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 54, 37, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 55, 48, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 97, 79, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 21, 75, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 24, 18, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 49, 90, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 145, 55, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 64, 59, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 16, 84, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 87, 36, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 23, 29, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 31, 20, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 119, 17, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 42, 0, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 128, 98, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (26, 132, 88, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 54, 20, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 112, 38, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 6, 38, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 108, 27, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 125, 99, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 65, 87, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 5, 41, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 28, 28, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 24, 5, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 99, 77, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 79, 53, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 129, 11, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 58, 45, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 70, 25, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 43, 95, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 90, 25, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 142, 6, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 60, 97, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 62, 93, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (27, 107, 100, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 91, 94, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 11, 12, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 4, 38, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 56, 14, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 95, 0, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 10, 57, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 61, 44, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 41, 25, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 24, 3, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 133, 64, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 112, 31, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 66, 100, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 36, 76, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 114, 10, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 30, 31, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 116, 61, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 111, 19, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 119, 46, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 28, 51, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (28, 126, 59, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 127, 23, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 5, 80, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 102, 97, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 49, 14, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 34, 92, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 42, 1, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 74, 31, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 109, 0, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 16, 75, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 128, 30, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 19, 9, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 61, 12, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 45, 5, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 129, 54, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 35, 86, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 115, 43, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 78, 57, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 70, 39, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 150, 91, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (29, 47, 83, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 7, 70, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 142, 72, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 68, 41, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 51, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 102, 11, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 103, 98, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 130, 12, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 134, 67, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 131, 22, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 117, 64, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 55, 66, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 144, 64, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 115, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 23, 5, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 16, 88, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 104, 34, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 35, 2, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 6, 60, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 81, 57, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (30, 77, 80, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 55, 0, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 83, 78, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 41, 81, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 66, 20, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 129, 34, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 19, 30, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 46, 68, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 7, 37, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 15, 44, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 6, 96, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 45, 21, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 108, 41, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 42, 96, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 106, 28, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 116, 88, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 84, 29, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 111, 37, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 81, 3, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 48, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (31, 95, 50, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 17, 38, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 62, 79, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 44, 1, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 89, 13, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 57, 68, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 94, 99, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 132, 52, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 119, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 22, 78, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 115, 63, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 79, 59, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 90, 97, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 74, 25, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 82, 63, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 49, 58, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 39, 33, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 96, 90, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 56, 3, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 1, 44, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (32, 20, 72, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 85, 59, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 87, 24, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 40, 71, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 68, 33, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 42, 21, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 59, 85, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 3, 91, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 147, 41, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 108, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 123, 71, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 110, 2, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 81, 39, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 135, 31, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 109, 15, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 129, 44, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 47, 43, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 49, 68, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 22, 6, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 70, 30, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (33, 141, 58, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 75, 88, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 16, 83, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 28, 12, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 5, 87, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 29, 26, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 139, 98, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 68, 86, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 100, 84, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 129, 61, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 22, 74, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 80, 46, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 138, 57, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 79, 29, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 141, 29, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 109, 55, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 59, 60, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 83, 42, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 146, 59, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 4, 35, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (34, 123, 25, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 116, 73, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 139, 67, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 78, 56, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 142, 88, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 17, 8, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 133, 22, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 42, 12, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 136, 0, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 33, 37, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 27, 58, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 9, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 114, 40, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 63, 12, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 46, 70, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 41, 13, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 65, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 28, 70, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 26, 36, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 60, 87, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (35, 59, 58, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 111, 73, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 88, 14, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 90, 84, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 76, 20, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 67, 63, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 101, 16, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 131, 94, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 133, 26, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 58, 23, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 39, 60, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 33, 15, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 150, 56, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 28, 53, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 23, 100, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 4, 24, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 8, 0, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 80, 25, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 10, 84, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 96, 83, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (36, 134, 18, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 23, 56, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 7, 31, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 124, 79, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 29, 30, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 37, 32, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 1, 42, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 44, 26, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 138, 70, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 6, 6, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 145, 97, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 68, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 45, 4, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 9, 96, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 108, 87, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 56, 53, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 4, 66, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 65, 65, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 50, 19, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 123, 21, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (37, 127, 6, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 31, 29, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 134, 81, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 84, 35, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 69, 22, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 144, 34, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 20, 83, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 85, 9, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 88, 99, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 131, 50, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 48, 33, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 72, 80, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 57, 97, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 63, 24, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 68, 49, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 108, 58, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 54, 17, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 18, 29, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 106, 39, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 132, 99, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (38, 19, 78, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 88, 28, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 89, 32, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 60, 92, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 31, 79, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 67, 39, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 102, 19, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 52, 92, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 87, 24, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 9, 9, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 17, 96, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 4, 88, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 137, 55, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 46, 78, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 81, 88, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 74, 33, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 7, 93, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 25, 41, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 147, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 113, 42, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (39, 83, 61, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 144, 12, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 126, 27, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 38, 46, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 5, 54, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 75, 100, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 68, 89, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 117, 89, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 60, 79, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 7, 45, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 147, 98, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 13, 61, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 130, 99, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 136, 41, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 31, 59, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 9, 18, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 102, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 146, 83, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 114, 83, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 51, 6, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (40, 56, 7, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 19, 27, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 53, 41, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 22, 49, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 145, 86, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 14, 45, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 59, 14, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 137, 6, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 107, 72, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 117, 84, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 1, 44, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 121, 69, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 31, 89, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 17, 41, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 74, 3, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 42, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 141, 78, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 110, 34, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 91, 6, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 15, 68, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (41, 49, 76, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 131, 9, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 75, 39, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 3, 32, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 29, 82, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 140, 74, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 89, 33, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 85, 35, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 61, 18, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 96, 38, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 31, 83, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 34, 33, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 149, 4, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 58, 97, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 98, 11, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 49, 46, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 11, 48, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 79, 29, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 44, 39, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 147, 44, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (42, 101, 36, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 93, 53, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 150, 59, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 3, 41, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 1, 40, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 65, 5, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 78, 10, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 80, 29, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 64, 49, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 105, 42, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 62, 2, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 121, 19, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 45, 67, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 24, 36, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 55, 75, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 26, 13, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 37, 84, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 76, 39, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 67, 10, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 13, 93, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (43, 17, 59, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 80, 4, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 88, 76, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 59, 57, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 32, 5, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 13, 21, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 129, 60, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 56, 25, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 78, 0, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 103, 38, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 17, 49, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 27, 92, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 60, 48, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 55, 12, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 130, 64, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 110, 1, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 97, 61, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 149, 76, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 31, 93, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 74, 74, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (44, 66, 0, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 18, 69, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 77, 50, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 4, 4, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 72, 34, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 60, 53, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 149, 42, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 115, 30, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 138, 60, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 121, 46, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 46, 27, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 66, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 30, 20, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 36, 48, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 2, 86, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 130, 89, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 95, 11, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 128, 81, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 28, 23, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 126, 28, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (45, 119, 0, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 4, 54, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 90, 43, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 65, 14, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 42, 49, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 147, 21, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 3, 52, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 87, 1, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 94, 38, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 45, 27, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 86, 25, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 81, 70, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 59, 36, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 19, 0, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 143, 16, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 21, 24, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 100, 4, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 110, 74, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 129, 87, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 131, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (46, 63, 15, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 85, 17, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 14, 39, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 66, 6, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 77, 23, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 104, 25, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 80, 30, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 21, 26, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 84, 6, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 54, 73, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 141, 30, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 78, 68, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 123, 4, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 103, 21, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 86, 18, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 92, 54, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 38, 69, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 39, 92, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 29, 12, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 7, 31, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (47, 127, 47, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 39, 50, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 150, 6, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 137, 15, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 42, 10, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 74, 97, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 120, 78, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 83, 3, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 99, 54, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 25, 93, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 52, 45, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 141, 30, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 146, 100, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 8, 65, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 63, 27, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 135, 21, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 127, 18, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 46, 22, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 142, 91, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 138, 2, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (48, 131, 5, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 19, 9, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 116, 24, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 82, 33, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 52, 58, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 103, 64, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 30, 76, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 118, 83, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 93, 9, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 89, 24, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 131, 90, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 142, 17, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 111, 40, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 39, 23, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 122, 8, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 43, 90, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 83, 82, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 31, 36, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 78, 35, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 147, 10, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (49, 42, 59, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 27, 8, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 98, 39, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 56, 59, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 134, 94, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 122, 14, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 74, 42, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 31, 47, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 52, 47, 0);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 44, 68, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 119, 51, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 131, 10, 1);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 61, 60, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 68, 82, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 35, 28, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 96, 69, 4);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 101, 4, 5);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 30, 100, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 120, 53, 3);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 57, 59, 2);
INSERT INTO Stats (match_id, player_id, runs, wickets) VALUES (50, 75, 81, 1);